### ISSUE TITLE
@schemastore npm scope

### ISSUE THREAD

**Issue by jrylan** [ffflorian/schemastore-updater#448]
Hi @ffflorian, 

First of all, thank you so much for what you've put together here. I'm glad to see someone else that values and utilizes JSON Schema as much as I do.

I am going to be implementing some automation using GitHub actions for the SchemaStore repo: <https://github.com/SchemaStore/schemastore/issues/1274>

I would like to build off the work you have here with a tighter integration with SchemaStore. One of the thoughts I have is to use GitHub actions to automatically publish the schemas to npm, with TypeScript types included by utilizing <https://github.com/bcherny/json-schema-to-typescript>.

Once this is all setup and ready to go, would you consider transferring the `schemastore` npm scope to @madskristensen (the founder of SchemaStore)?

**Comment by ffflorian** [comment]
Hi @jrylan,

good to hear you like my little project! Although it for sure needs some more attention from people with more time on their hands 🙂.

I'm okay with handing over the `schemastore` npm scope to @madskristensen, and I'd be happy if you could mention me somewhere in the SchemaStore repository.

Looking forward to seeing JSON schemas being published "officially"! 🎉

**Comment by jrylan** [comment]
Hey @ffflorian! Thank you so much! I'll ping you again when I'm closer to being finished, it will be within the next two weeks (hopefully sooner). You can feel free to give @madskristensen access to the org anytime, or just wait until I'm ready. Completely up to you.

When I submit my PR, I will definitely include a thank you to you for the npm scope in the project.

**Comment by ffflorian** [comment]
@madskristensen I just invited you as a member to `@schemastore` on npm and will set you as owner as soon as you accept the invitation.

**Comment by madskristensen** [comment]
@ffflorian Thanks, but I haven't seen the invite yet. It's not in my spam filter or visible on the npm website.

**Comment by ffflorian** [comment]
@madskristensen strange. Please send me an email to npm@ffflorian.de then we can work out the details.

**Comment by ffflorian** [comment]
Short update: I am still waiting for @madskristensen to accept my invitation.

**Comment by madskristensen** [comment]
Yay, thanks @ffflorian

**Comment by jrylan** [comment]
@madskristensen @ffflorian awesome, thank you! I posted over on schemastore that I have some unexpected downtime while getting my computed repaired, I'm expecting it back early next week. I am about 80% ready to submit my PR. Thank you!
