### ISSUE TITLE
UI5 manifest type definitions are now officially produced

### ISSUE THREAD

**Issue by akudev** [ffflorian/schemastore-updater#656]
Hi,
the team maintaining the manifest structure now officially generates type definitions.
They can be found at https://github.com/SAP/ui5-manifest/blob/master/types/manifest.d.ts 
And in the npm package (https://www.npmjs.com/package/@ui5/manifest) starting from version 1.51.0.

Maybe you want to mention this in the README.

Regards
Andreas

**Comment by ffflorian** [comment]
Hi @akudev, thanks for the hint. I’ll deprecate the types on npm and add a link to your repo.

**Comment by ffflorian** [comment]
Done in https://github.com/ffflorian/schemastore-updater/commit/49792ec13a2cd352741c3d7d3c4a1ca553e2aea7, also see [`@schemastore/ui5-manifest` on npm](https://www.npmjs.com/package/@schemastore/ui5-manifest).

**Comment by akudev** [comment]
Thanks a lot!
